title: <p align="center"> Amrit Dhakal </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  Xi'an, China
  <br> (+86) 15686251556
  <br> amrit.dhakal.585@hotmail.com
  <br> WeChat Id- htppkMhm6_fnB2AQJnq
  </p>
  
  <p align="justify">
  I am a <b>Aerospace Engineer</b> with extensive research on data science, CFD and electric powertrain.
  <br>
  I am currently studying <b>Master's Degree in Aerospace Science and technology at Northwestern Polytechnical University(NPU)</b>, where I received solid training in all the major fields of computational fluid dynamics, electric powertrain and data science.
  <br>
  I have a deeply rooted science education background, having achieved a <b>Bachelor's Degree in Aerospace Engineering</b>.
  <br>
  I consider myself a kind, empathetic, creative and determined person. I am pragmatic and organized, yet flexible.
  <br><br>
  </p>
theme: jekyll-theme-minimal