title: <p align="center"> Amrit Dhakal </p>
theme: jekyll-theme-minimal
#logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  Xi'an, China
  <br> (+86) 15686251556
  <br> amrit.dhakal.585@homatil.com
  <a href="https://www.wechat.com">WeChat Id :- htppkMhm6_fnB2AQJnq</a>
  </p>
  
  <p align="justify">
  I am a <b>Aerospace Engineer</b> who enjoys connecting the dots by the use of technology. 
  <br>
  I am currently studying <b>Master's Degree in Aerospace Science and technology at Northwestern Polytechnical University(NPU)</b>, where I received solid training in all the major fields of Aerospace technologies and Data science.
  <br>
  I have a deeply rooted science education background, having achieved a <b>Bachelor's Degree in Aerospace Engineering</b>.
  <br>
  I consider myself a kind, empathetic, creative and determined person. I am pragmatic and organized, yet flexible.
  <br><br>
  </p>
